version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: photocard
      POSTGRES_PASSWORD: photocard
      POSTGRES_DB: photocard
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: ./apps/api
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"
    volumes:
      - output:/app/output

  worker:
    build: ./apps/worker
    env_file: .env
    depends_on:
      - api
      - redis
    volumes:
      - output:/app/output

  portal:
    build: ./apps/portal
    env_file: .env
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  pgdata:
  output:

